apiVersion: v1
kind: Namespace
metadata:
  name: airflow-staging
---
apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  type: LoadBalancer
  ports:
  - port: 8085
  selector:
    name: airflow
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-permissions
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: spark-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: spark-operator
---
# Role for spark-on-k8s-operator to create resources on cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-cluster-cr
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
rules:
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - sparkapplications
    verbs:
      - '*'
---
# Allow airflow-worker service account access for spark-on-k8s
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-spark-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-cluster-cr
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: airflow-staging
---
# Allow airflow-worker service account access for spark-on-k8s
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-pods
  namespace: airflow-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pods-permissions
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: airflow-staging
---
kind: PersistentVolume
apiVersion: v1
metadata:
 name: airflow-dags
spec:
 storageClassName: manual
 accessModes:
 - ReadWriteMany
 capacity:
   storage: 2Gi
 hostPath:
   path: /airflow-dags/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: airflow-dags
spec:
 storageClassName: manual
 accessModes:
 - ReadWriteMany
 resources:
  requests:
   storage: 2Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
 name: airflow-logs
spec:
 storageClassName: manual
 accessModes:
 - ReadWriteMany
 capacity:
   storage: 2Gi
 hostPath:
   path: /airflow-logs/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: airflow-logs
spec:
 storageClassName: manual
 accessModes:
 - ReadWriteMany
 resources:
  requests:
   storage: 2Gi
---